### ISSUE TITLE
로그인 안됨 

### ISSUE THREAD

**Issue by keesun** [spring-sprout/osoon#44]
## Description

DB 3.3으로 올린 뒤부터 인지 언제부턴지 정확히 모르겠음.

```
java.lang.IllegalArgumentException: Can not set java.lang.Long field io.osoon.data.domain.User.id to io.osoon.data.domain.User
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.neo4j.ogm.metadata.FieldInfo.read(FieldInfo.java:373)
	at org.neo4j.ogm.metadata.FieldInfo.readProperty(FieldInfo.java:432)
	at org.neo4j.ogm.utils.EntityUtils.identity(EntityUtils.java:54)
	at org.neo4j.ogm.context.MappingContext.nativeId(MappingContext.java:475)
	at org.neo4j.ogm.context.EntityGraphMapper.getNodeBuilder(EntityGraphMapper.java:273)
	at org.neo4j.ogm.context.EntityGraphMapper.mapEntity(EntityGraphMapper.java:216)
	at org.neo4j.ogm.context.EntityGraphMapper.map(EntityGraphMapper.java:127)
	at org.neo4j.ogm.session.delegates.SaveDelegate.save(SaveDelegate.java:80)
	at org.neo4j.ogm.session.delegates.SaveDelegate.save(SaveDelegate.java:41)
	at org.neo4j.ogm.session.Neo4jSession.save(Neo4jSession.java:451)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

App을 실행하고 로그인 시도하면 이런 에러가 발생하는데, UserRepositoryTest에서는 에러가 발생하지 않음.. 흐음...

**Comment by keesun** [comment]
의존성 정리하니까 해결 됨... 아 빡쎄다 정말.. 이거 때문에 3시간은 날린듯.. 아 슬퍼..

**Comment by KimJejun** [comment]
고생하셨습니다. 
어서 부트 2.0 릴리즈 나왔으면..
